<a href="https://colab.research.google.com/github/jklbiz/sector-cycle-portfolio-strategy/blob/main/fn%EC%A7%80%EC%88%98_10%EA%B0%9C_%EC%84%B9%ED%84%B0_%EC%82%AC%EC%9D%B4%ED%82%B7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report,confusion_matrix
from keras import models
from keras import layers

In [ ]:
from google.colab import files
upload=files.upload()

Saving 데이터5.xlsx to 데이터5.xlsx

In [ ]:
df=pd.read_excel('데이터5.xlsx')

df_date=df.set_index('Symbol Name')

df_reset = df.drop(['Symbol Name'], axis = 1)

In [ ]:
df

     Symbol Name  en_num  in_num  lux_num  ...  it_num  ut_num  tr_num  co_num
0     2000-01-08       9       4        8  ...      10       1       5       6
1     2000-01-15      10       4        5  ...       7       1       9       8
2     2000-01-22       6       7        8  ...       4       2      10       9
3     2000-01-29       9       6        8  ...       5       3      10       7
4     2000-02-05       9       5        6  ...       8       2      10       7
...          ...     ...     ...      ...  ...     ...     ...     ...     ...
1084  2020-10-17       3       7        5  ...       4      10       8       9
1085  2020-10-24       3       7        5  ...       4      10       8       9
1086  2020-10-31       3       7        5  ...       4      10       8       9
1087  2020-11-07       3       7        5  ...       4      10       8       9
1088  2020-11-13       3       7        5  ...       4      10       8       9

[1089 rows x 11 columns]

In [ ]:
energy=df['en_num'].values
industrial = df['in_num'].values
luxury = df['lux_num'].values
essential = df['es_num'].values
health = df['he_num'].values
finance = df['fi_num'].values
it = df['it_num'].values
utility = df['ut_num'].values
transport = df['tr_num'].values
construct = df['co_num'].values

In [ ]:
energy=energy[3:]
industrial=industrial[3:]
luxury=luxury[3:]
essential=essential[3:]
health=health[3:]
finance=finance[3:]
it=it[3:]
utility=utility[3:]
transport=transport[3:]
construct=construct[3:]

In [ ]:
df_late1=df_reset.loc[:1085,:]
df_late2=df_reset.loc[1:1086,:]
df_late3=df_reset.loc[2:1087,:]

np_late1=df_late1.values
np_late2=df_late2.values
np_late3=df_late3.values

df_late11=pd.DataFrame(np_late1,columns=['en_num1',	'in_num1',	'lux_num1',	'es_num1',	'he_num1',	'fi_num1','it_num1'	,'ut_num1'	,'tr_num1'	,'co_num1'])
df_late22=pd.DataFrame(np_late2,columns=['en_num2',	'in_num2',	'lux_num2',	'es_num2',	'he_num2',	'fi_num2','it_num2'	,'ut_num2'	,'tr_num2'	,'co_num2'])
df_late33=pd.DataFrame(np_late3,columns=['en_num3',	'in_num3',	'lux_num3',	'es_num3',	'he_num3',	'fi_num3','it_num3'	,'ut_num3'	,'tr_num3'	,'co_num3'])

In [ ]:
df_late.iloc[50:,:]

      en_num1  in_num1  lux_num1  es_num1  ...  ut_num3  tr_num3  co_num3  construct
50          5        7         6        2  ...        2        8        9          9
51          4        7         6        2  ...        4        8        9         10
52          5        7         6        3  ...        4        9       10          8
53          5        7         6        3  ...        4        9        8          8
54          6        7         5        3  ...        3       10        8          8
...       ...      ...       ...      ...  ...      ...      ...      ...        ...
1081        3        7         5        2  ...       10        8        9          9
1082        3        7         5        2  ...       10        8        9          9
1083        3        7         5        2  ...       10        8        9          9
1084        3        7         5        2  ...       10        8        9          9
1085        3        7         5        2  ...       10        8        9          9

[1036 rows x 31 columns]

In [ ]:
#####energy
df_late=pd.concat([df_late11,df_late22,df_late33],axis=1)

df_late['energy']=energy

df_late

y_energy_df = df_late['energy']
X_energy_df= df_late.drop('energy',axis=1)

X_train, X_test, y_train, y_test=train_test_split(X_energy_df, y_energy_df, test_size=0.2, shuffle=False, random_state=11)
# Classifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
lr_clf = LogisticRegression(random_state=11,max_iter= 10000)
dt_clf.fit(X_train , y_train)
dt_pred = dt_clf.predict(X_test)
print('DecisionTreeClassifier 정확도: {0:.4f}'.format(accuracy_score(y_test, dt_pred)))
rf_clf.fit(X_train , y_train)
rf_pred = rf_clf.predict(X_test)
print('RandomForestClassifier 정확도:{0:.4f}'.format(accuracy_score(y_test, rf_pred)))
lr_clf.fit(X_train , y_train)
lr_pred = lr_clf.predict(X_test)
print('LogisticRegression 정확도: {0:.4f}'.format(accuracy_score(y_test, lr_pred)))
pred_energy=dt_pred

DecisionTreeClassifier 정확도: 0.9862
RandomForestClassifier 정확도:0.9817
LogisticRegression 정확도: 0.9220

In [ ]:
#####industrial
df_late=pd.concat([df_late11,df_late22,df_late33],axis=1)
df_late['industrial']=industrial

df_late

y_energy_df = df_late['industrial']
X_energy_df= df_late.drop('industrial',axis=1)

X_train, X_test, y_train, y_test=train_test_split(X_energy_df, y_energy_df, test_size=0.2,shuffle=False, random_state=11)
# Classifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
lr_clf = LogisticRegression(random_state=11,max_iter= 10000)
dt_clf.fit(X_train , y_train)
dt_pred = dt_clf.predict(X_test)
print('DecisionTreeClassifier 정확도: {0:.4f}'.format(accuracy_score(y_test, dt_pred)))
rf_clf.fit(X_train , y_train)
rf_pred = rf_clf.predict(X_test)
print('RandomForestClassifier 정확도:{0:.4f}'.format(accuracy_score(y_test, rf_pred)))
lr_clf.fit(X_train , y_train)
lr_pred = lr_clf.predict(X_test)
print('LogisticRegression 정확도: {0:.4f}'.format(accuracy_score(y_test, lr_pred)))
pred_industrial=dt_pred

DecisionTreeClassifier 정확도: 0.9908
RandomForestClassifier 정확도:0.3303
LogisticRegression 정확도: 0.4174

In [ ]:
#####luxury
df_late=pd.concat([df_late11,df_late22,df_late33],axis=1)
df_late['luxury']=luxury
df_late

y_energy_df = df_late['luxury']
X_energy_df= df_late.drop('luxury',axis=1)

X_train, X_test, y_train, y_test=train_test_split(X_energy_df, y_energy_df, test_size=0.2,shuffle=False, random_state=11)
# Classifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
lr_clf = LogisticRegression(random_state=11,max_iter= 10000)
dt_clf.fit(X_train , y_train)
dt_pred = dt_clf.predict(X_test)
print('DecisionTreeClassifier 정확도: {0:.4f}'.format(accuracy_score(y_test, dt_pred)))
rf_clf.fit(X_train , y_train)
rf_pred = rf_clf.predict(X_test)
print('RandomForestClassifier 정확도:{0:.4f}'.format(accuracy_score(y_test, rf_pred)))
lr_clf.fit(X_train , y_train)
lr_pred = lr_clf.predict(X_test)
print('LogisticRegression 정확도: {0:.4f}'.format(accuracy_score(y_test, lr_pred)))
pred_luxury=rf_pred

DecisionTreeClassifier 정확도: 0.2064
RandomForestClassifier 정확도:0.6560
LogisticRegression 정확도: 0.4404

In [ ]:
#####essential
df_late=pd.concat([df_late11,df_late22,df_late33],axis=1)
df_late['essential']=essential

df_late

y_energy_df = df_late['essential']
X_energy_df= df_late.drop('essential',axis=1)

X_train, X_test, y_train, y_test=train_test_split(X_energy_df, y_energy_df, test_size=0.2,shuffle=False, random_state=11)
# Classifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
lr_clf = LogisticRegression(random_state=11,max_iter= 10000)
dt_clf.fit(X_train , y_train)
dt_pred = dt_clf.predict(X_test)
print('DecisionTreeClassifier 정확도: {0:.4f}'.format(accuracy_score(y_test, dt_pred)))
rf_clf.fit(X_train , y_train)
rf_pred = rf_clf.predict(X_test)
print('RandomForestClassifier 정확도:{0:.4f}'.format(accuracy_score(y_test, rf_pred)))
lr_clf.fit(X_train , y_train)
lr_pred = lr_clf.predict(X_test)
print('LogisticRegression 정확도: {0:.4f}'.format(accuracy_score(y_test, lr_pred)))
pred_essential=rf_pred

DecisionTreeClassifier 정확도: 0.7523
RandomForestClassifier 정확도:0.9862
LogisticRegression 정확도: 0.2890

In [ ]:
#####health
df_late=pd.concat([df_late11,df_late22,df_late33],axis=1)
df_late['health']=health
df_late

y_energy_df = df_late['health']
X_energy_df= df_late.drop('health',axis=1)

X_train, X_test, y_train, y_test=train_test_split(X_energy_df, y_energy_df, test_size=0.2, shuffle=False,random_state=11)
# Classifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
lr_clf = LogisticRegression(random_state=11,max_iter= 10000)
dt_clf.fit(X_train , y_train)
dt_pred = dt_clf.predict(X_test)
print('DecisionTreeClassifier 정확도: {0:.4f}'.format(accuracy_score(y_test, dt_pred)))
rf_clf.fit(X_train , y_train)
rf_pred = rf_clf.predict(X_test)
print('RandomForestClassifier 정확도:{0:.4f}'.format(accuracy_score(y_test, rf_pred)))
lr_clf.fit(X_train , y_train)
lr_pred = lr_clf.predict(X_test)
print('LogisticRegression 정확도: {0:.4f}'.format(accuracy_score(y_test, lr_pred)))
pred_health=dt_pred

DecisionTreeClassifier 정확도: 0.9954
RandomForestClassifier 정확도:0.2339
LogisticRegression 정확도: 0.3349

In [ ]:
#####finance
df_late=pd.concat([df_late11,df_late22,df_late33],axis=1)
df_late['finance']=finance

df_late

y_energy_df = df_late['finance']
X_energy_df= df_late.drop('finance',axis=1)

X_train, X_test, y_train, y_test=train_test_split(X_energy_df, y_energy_df, test_size=0.2,shuffle=False, random_state=11)
# Classifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
lr_clf = LogisticRegression(random_state=11,max_iter= 10000)
dt_clf.fit(X_train , y_train)
dt_pred = dt_clf.predict(X_test)
print('DecisionTreeClassifier 정확도: {0:.4f}'.format(accuracy_score(y_test, dt_pred)))
rf_clf.fit(X_train , y_train)
rf_pred = rf_clf.predict(X_test)
print('RandomForestClassifier 정확도:{0:.4f}'.format(accuracy_score(y_test, rf_pred)))
lr_clf.fit(X_train , y_train)
lr_pred = lr_clf.predict(X_test)
print('LogisticRegression 정확도: {0:.4f}'.format(accuracy_score(y_test, lr_pred)))
pred_finance=dt_pred

DecisionTreeClassifier 정확도: 0.9220
RandomForestClassifier 정확도:0.4312
LogisticRegression 정확도: 0.6697

In [ ]:
#####it
df_late=pd.concat([df_late11,df_late22,df_late33],axis=1)
df_late['it']=it

df_late

y_energy_df = df_late['it']
X_energy_df= df_late.drop('it',axis=1)

X_train, X_test, y_train, y_test=train_test_split(X_energy_df, y_energy_df, test_size=0.2,shuffle=False, random_state=11)
# Classifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
lr_clf = LogisticRegression(random_state=11,max_iter= 10000)
dt_clf.fit(X_train , y_train)
dt_pred = dt_clf.predict(X_test)
print('DecisionTreeClassifier 정확도: {0:.4f}'.format(accuracy_score(y_test, dt_pred)))
rf_clf.fit(X_train , y_train)
rf_pred = rf_clf.predict(X_test)
print('RandomForestClassifier 정확도:{0:.4f}'.format(accuracy_score(y_test, rf_pred)))
lr_clf.fit(X_train , y_train)
lr_pred = lr_clf.predict(X_test)
print('LogisticRegression 정확도: {0:.4f}'.format(accuracy_score(y_test, lr_pred)))
pred_it=dt_pred

DecisionTreeClassifier 정확도: 0.8578
RandomForestClassifier 정확도:0.0183
LogisticRegression 정확도: 0.0229

In [ ]:
#####utility
df_late=pd.concat([df_late11,df_late22,df_late33],axis=1)
df_late['utility']=utility
df_late

y_energy_df = df_late['utility']
X_energy_df= df_late.drop('utility',axis=1)

X_train, X_test, y_train, y_test=train_test_split(X_energy_df, y_energy_df, test_size=0.2, shuffle=False,random_state=11)
# Classifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
lr_clf = LogisticRegression(random_state=11,max_iter= 10000)
dt_clf.fit(X_train , y_train)
dt_pred = dt_clf.predict(X_test)
print('DecisionTreeClassifier 정확도: {0:.4f}'.format(accuracy_score(y_test, dt_pred)))
rf_clf.fit(X_train , y_train)
rf_pred = rf_clf.predict(X_test)
print('RandomForestClassifier 정확도:{0:.4f}'.format(accuracy_score(y_test, rf_pred)))
lr_clf.fit(X_train , y_train)
lr_pred = lr_clf.predict(X_test)
print('LogisticRegression 정확도: {0:.4f}'.format(accuracy_score(y_test, lr_pred)))
pred_utility=dt_pred

DecisionTreeClassifier 정확도: 0.7661
RandomForestClassifier 정확도:0.7615
LogisticRegression 정확도: 0.7294

In [ ]:
#####transport
df_late=pd.concat([df_late11,df_late22,df_late33],axis=1)
df_late['transport']=transport

df_late

y_energy_df = df_late['transport']
X_energy_df= df_late.drop('transport',axis=1)

X_train, X_test, y_train, y_test=train_test_split(X_energy_df, y_energy_df, test_size=0.2, shuffle=False,random_state=11)
# Classifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
lr_clf = LogisticRegression(random_state=11,max_iter= 10000)
dt_clf.fit(X_train , y_train)
dt_pred = dt_clf.predict(X_test)
print('DecisionTreeClassifier 정확도: {0:.4f}'.format(accuracy_score(y_test, dt_pred)))
rf_clf.fit(X_train , y_train)
rf_pred = rf_clf.predict(X_test)
print('RandomForestClassifier 정확도:{0:.4f}'.format(accuracy_score(y_test, rf_pred)))
lr_clf.fit(X_train , y_train)
lr_pred = lr_clf.predict(X_test)
print('LogisticRegression 정확도: {0:.4f}'.format(accuracy_score(y_test, lr_pred)))
pred_transport=rf_pred

DecisionTreeClassifier 정확도: 0.5872
RandomForestClassifier 정확도:0.8119
LogisticRegression 정확도: 0.6147

In [ ]:
#####construct
df_late=pd.concat([df_late11,df_late22,df_late33],axis=1)
df_late['construct']=construct

df_late

y_energy_df = df_late['construct']
X_energy_df= df_late.drop('construct',axis=1)

X_train, X_test, y_train, y_test=train_test_split(X_energy_df, y_energy_df, test_size=0.2,shuffle=False, random_state=11)
# Classifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
lr_clf = LogisticRegression(random_state=11,max_iter= 10000)
dt_clf.fit(X_train , y_train)
dt_pred = dt_clf.predict(X_test)
print('DecisionTreeClassifier 정확도: {0:.4f}'.format(accuracy_score(y_test, dt_pred)))
rf_clf.fit(X_train , y_train)
rf_pred = rf_clf.predict(X_test)
print('RandomForestClassifier 정확도:{0:.4f}'.format(accuracy_score(y_test, rf_pred)))
lr_clf.fit(X_train , y_train)
lr_pred = lr_clf.predict(X_test)
print('LogisticRegression 정확도: {0:.4f}'.format(accuracy_score(y_test, lr_pred)))
pred_construct=dt_pred

DecisionTreeClassifier 정확도: 0.9037
RandomForestClassifier 정확도:0.8899
LogisticRegression 정확도: 0.8073

In [ ]:
df_results=pd.DataFrame()

In [ ]:
df_results['energy']=pred_energy
df_results['industrial']=pred_industrial
df_results['luxury']=pred_luxury
df_results['essential']=pred_essential
df_results['health']=pred_health
df_results['finance']=pred_finance
df_results['it']=pred_it
df_results['utility']=pred_utility
df_results['transport']=pred_transport
df_results['construct']=pred_construct

In [ ]:
df_results

     energy  industrial  luxury  essential  ...  it  utility  transport  construct
0         3           6       4          1  ...   8        9          9         10
1         3           6       4          1  ...   8        9          9         10
2         3           6       4          1  ...   8        9          9         10
3         3           6       4          1  ...   8        9          9         10
4         3           6       4          1  ...   9        9          9         10
..      ...         ...     ...        ...  ...  ..      ...        ...        ...
213       3           7       3          2  ...   4        8          8          9
214       3           7       3          2  ...   4        8          8          9
215       3           7       3          2  ...   4        8          8          9
216       3           7       3          2  ...   4        8          8          9
217       3           7       3          2  ...   4        8          8          9

[218 rows x 10 columns]

In [ ]:
df_results.to_csv('df_results.csv')
files.download('df_results.csv')